/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Clases.ColumnaRenderer;
import javax.swing.table.DefaultTableModel;
import producción.VentanaPrincipal;

/**
 *
 * @author panda
 */
public class PlanAgregado extends javax.swing.JInternalFrame {

    public static DefaultTableModel mimodelo;
 
    
    public PlanAgregado() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Numero_trab = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1800, 1500, 1100, 900, 1100, 1600, 1800, 1500, 1100, 900, 1100, 1600},
                {22, 19, 21, 21, 22, 20,22, 20, 21, 21, 22, 20 }
            },
            new String [] {
                "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return true;
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Materiales");

        jLabel11.setText("Cto de Mantenimiento de Inv");

        jLabel12.setText("Cto Marginal de Inventario");

        jTextField11.setText("5");

        jLabel13.setText("Cto Marginal de subcontracion");

        jLabel2.setText("Cto de Contratacion y Capacitacion");

        jLabel14.setText("Cto de Despido");

        jTextField14.setText("250");

        jLabel15.setText("Horas Laborales Req");

        jLabel16.setText("Cto del Tiempo Normal");

        jTextField16.setText("4");

        jLabel17.setText("Cto del Tiempo Extra");

        jTextField18.setText("200");

        jLabel18.setText("Inventario Inicial");

        jTextField13.setText("400");

        jLabel19.setText("Inventario de seguridad");

        jTextField19.setText("0.25");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Generar");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("Tipo de Metodo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Método", "Persecución", "Fuerza Nivelada y Horas Extras", "Fuerza Nivelada y Outsourcing", " " }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jLabel5.setText("Numero de Trabajadores Iniciales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel11))
                                    .addGap(77, 77, 77)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(168, 168, 168)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(90, 90, 90)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel14))
                                        .addGap(122, 122, 122)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(69, 69, 69)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Numero_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField16)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(Numero_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      
        switch(jComboBox1.getSelectedIndex()){
        
            case 1: Metodo_Persecucion();
                break;
            case 2: Metodo_Fuerza_nivelada();
                break;
            case 3: Metodo_Outsourcing();
                break;
            
        }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    public void Metodo_Outsourcing(){
    
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        mimodelo = new DefaultTableModel(){
        
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        
        };
        mimodelo.addColumn("Meses", new String[]{
            
            "Requerimiento de Produccion","Horas de Produccion Requeridas",
            "Dias Habiles por mes","Horas al mes por trabajar",
            "Horas Totales Disponibles","Unidades Producidas",
            "Unidades Faltantes","Unidades sobrantes","Costo del Tiempo Normal",
            "Costo de subcontratación","Horas mantenimiento","Total"
        });
        mimodelo.addColumn("Enero");
        mimodelo.addColumn("Febrero");
        mimodelo.addColumn("Marzo");
        mimodelo.addColumn("Abril");
        mimodelo.addColumn("Mayo");
        mimodelo.addColumn("Junio");
        mimodelo.addColumn("Julio");
        mimodelo.addColumn("Agosto");
        mimodelo.addColumn("Septiembre");
        mimodelo.addColumn("Octubre");
        mimodelo.addColumn("Noviembre");
        mimodelo.addColumn("Diciembre");
        
        double btn_inventario_seguridad = Double.parseDouble(jTextField19.getText().trim());
        double btn_inventario_inicial = Double.parseDouble(jTextField13.getText().trim());
        double btn_costo_marginal_inventario = Double.parseDouble(jTextField11.getText().trim());
        double btn_costo_producto = Double.parseDouble(jTextField9.getText().trim());
        double btn_costo_outsourcing = Double.parseDouble(jTextField12.getText().trim());
        double btn_costo_tiempo_normal = Double.parseDouble(jTextField16.getText().trim());
        double btn_trabajadores_iniciales = Double.parseDouble(Numero_trab.getText().trim());
        double bnt_costo_mantenimiento = Double.parseDouble(jTextField10.getText().trim());
        double tot = 0;
        
        for(int i=1;i<=modelo.getColumnCount();i++){
           double dato = Double.parseDouble(modelo.getValueAt(0, i-1).toString());
           double dato_1 = dato*btn_inventario_seguridad;
           double PrimeraFila = dato+dato_1-btn_inventario_inicial;
           double SegundaFila = PrimeraFila*btn_costo_marginal_inventario;
           double TerceraFila = Double.parseDouble(modelo.getValueAt(1, i-1).toString());
           double CuartaFila =  8*TerceraFila;
           double QuintaFila = btn_trabajadores_iniciales*8*TerceraFila;
           double SextaFila = QuintaFila/btn_costo_marginal_inventario;
           double SeptimaFila = PrimeraFila-SextaFila;
                if (SeptimaFila <=-1){
                    SeptimaFila = 0;
                }
           
           double OctabaFila = SextaFila-PrimeraFila;
                if (OctabaFila <=-1){
                     OctabaFila = 0;
                 }
           double NovenaFila = SegundaFila*btn_costo_tiempo_normal;
           double DecimaFila = SeptimaFila*(btn_costo_outsourcing-btn_costo_producto);
           double OnceabaFila = OctabaFila*bnt_costo_mantenimiento;
           double Doceaba = NovenaFila+DecimaFila+OnceabaFila;
           tot+=Doceaba;
           
           //Hacen falta validaciones en el faltante y en los meses que no se esten evaluando 
           
           mimodelo.setValueAt(PrimeraFila, 0, i);
           mimodelo.setValueAt(SegundaFila, 1, i);
           mimodelo.setValueAt(TerceraFila, 2, i);
           mimodelo.setValueAt(CuartaFila, 3, i);
           mimodelo.setValueAt(QuintaFila, 4, i);
           mimodelo.setValueAt(SextaFila, 5, i);
           mimodelo.setValueAt(SeptimaFila, 6, i);
           mimodelo.setValueAt(OctabaFila, 7, i);
           mimodelo.setValueAt(NovenaFila, 8, i);
           mimodelo.setValueAt(DecimaFila, 9, i);
           mimodelo.setValueAt(OnceabaFila, 10, i);
           btn_inventario_inicial  = dato_1;
           
        }
        
        mimodelo.setValueAt(tot, 11, 1);
        
        Metodo metodo = new Metodo();
        metodo.setVisible(true);
        VentanaPrincipal.fondoInternal.add(metodo);
        metodo.p = this;
        this.setVisible(false);
    
    }
    
    public void Metodo_Fuerza_nivelada() {
       
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        mimodelo = new DefaultTableModel(){
        
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        
        };
        mimodelo.addColumn("Meses", new String[]{
            
            "Produccion requeridas","Horas de Produccion Requeridas",
            "Dias laborables","Horas disponibles / mes",
            "Horas total diponibles","Horas extras requeridas",
            "Horas ociosas","Costo de produccion (Hrs/ normal)","Costo de horas extra",
            "Subtotal","Total"
        });
        mimodelo.addColumn("Enero");
        mimodelo.addColumn("Febrero");
        mimodelo.addColumn("Marzo");
        mimodelo.addColumn("Abril");
        mimodelo.addColumn("Mayo");
        mimodelo.addColumn("Junio");
        mimodelo.addColumn("Julio");
        mimodelo.addColumn("Agosto");
        mimodelo.addColumn("Septiembre");
        mimodelo.addColumn("Octubre");
        mimodelo.addColumn("Noviembre");
        mimodelo.addColumn("Diciembre");
        
        double btn_inventario_seguridad = Double.parseDouble(jTextField19.getText().trim());
        double btn_inventario_inicial = Double.parseDouble(jTextField13.getText().trim());
        double btn_costo_inventario_agotado = Double.parseDouble(jTextField11.getText().trim());
        double btn_costo_capacitacion = Double.parseDouble(jTextField18.getText().trim());
        double btn_costo_despido = Double.parseDouble(jTextField14.getText().trim());
        double btn_costo_tiempo_normal = Double.parseDouble(jTextField16.getText().trim());
        double btn_costo_tiempo_extra = Double.parseDouble(jTextField17.getText().trim());
        double numero_trab =Double.parseDouble(Numero_trab.getText().trim());
        double tot = 0;
        
        for(int i=1;i<=modelo.getColumnCount();i++){
           double dato = Double.parseDouble(modelo.getValueAt(0, i-1).toString());
           double dato_1 = dato*btn_inventario_seguridad;
           double PrimeraFila = dato+dato_1-btn_inventario_inicial;
           double SegundaFila = PrimeraFila*btn_costo_inventario_agotado;
           double TerceraFila = Double.parseDouble(modelo.getValueAt(1, i-1).toString());
           double CuartaFila =  8*TerceraFila;
           double QuintaFila = numero_trab*CuartaFila;
           double SextaFila ;
           double SeptimaFila;
           if(QuintaFila-SegundaFila > 0){
           
            SextaFila = 0;
            SeptimaFila = QuintaFila-SegundaFila;
           }
           else if(QuintaFila-SegundaFila < 0)
           {
          SextaFila = SegundaFila-QuintaFila;
           SeptimaFila = 0;
        }
           else{
           
            SextaFila = 0;
            SeptimaFila = 0;
           }
       
           double OctabaFila = SegundaFila*btn_costo_tiempo_normal;
           double NovenaFila = SextaFila*btn_costo_tiempo_extra;
           double DecimaFila = OctabaFila+NovenaFila;
           tot+=DecimaFila;
           mimodelo.setValueAt(PrimeraFila, 0, i);
           mimodelo.setValueAt(SegundaFila, 1, i);
           mimodelo.setValueAt(TerceraFila, 2, i);
           mimodelo.setValueAt(CuartaFila, 3, i);
           mimodelo.setValueAt(QuintaFila, 4, i);
           mimodelo.setValueAt(SextaFila, 5, i);
           mimodelo.setValueAt(SeptimaFila, 6, i);
           mimodelo.setValueAt(OctabaFila, 7, i);
           mimodelo.setValueAt(NovenaFila, 8, i);
           mimodelo.setValueAt(DecimaFila, 9, i);
          
           btn_inventario_inicial  = dato_1;
           
        }
        
        mimodelo.setValueAt(tot, 10, 1);
        
        Metodo metodo = new Metodo();
        metodo.setVisible(true);
        VentanaPrincipal.fondoInternal.add(metodo);
        metodo.p = this;
        this.setVisible(false);

}

    public void Metodo_Persecucion(){
    
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        mimodelo = new DefaultTableModel(){
        
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        
        };
        mimodelo.addColumn("Meses", new String[]{
            
            "Requerimiento de Produccion","Horas de Produccion Requeridas",
            "Dias Habiles por mes","Horas al mes por trabajar",
            "Trabajadores Requeridos","Nuevo Trabajadores contratados",
            "Costo de contratacion","Despido de Trabajadores","Costo de Despido",
            "Costo del Tiempo Normal","Subtotal","Total"
        });
        mimodelo.addColumn("Enero");
        mimodelo.addColumn("Febrero");
        mimodelo.addColumn("Marzo");
        mimodelo.addColumn("Abril");
        mimodelo.addColumn("Mayo");
        mimodelo.addColumn("Junio");
        mimodelo.addColumn("Julio");
        mimodelo.addColumn("Agosto");
        mimodelo.addColumn("Septiembre");
        mimodelo.addColumn("Octubre");
        mimodelo.addColumn("Noviembre");
        mimodelo.addColumn("Diciembre");
        
        double btn_inventario_seguridad = Double.parseDouble(jTextField19.getText().trim());
        double btn_inventario_inicial = Double.parseDouble(jTextField13.getText().trim());
        double btn_costo_inventario_agotado = Double.parseDouble(jTextField11.getText().trim());
        double btn_costo_capacitacion = Double.parseDouble(jTextField18.getText().trim());
        double btn_costo_despido = Double.parseDouble(jTextField14.getText().trim());
        double btn_costo_tiempo_normal = Double.parseDouble(jTextField16.getText().trim());
        double tot = 0;
        
        for(int i=1;i<=modelo.getColumnCount();i++){
           double dato = Double.parseDouble(modelo.getValueAt(0, i-1).toString());
           double dato_1 = dato*btn_inventario_seguridad;
           double PrimeraFila = dato+dato_1-btn_inventario_inicial;
           double SegundaFila = PrimeraFila*btn_costo_inventario_agotado;
           double TerceraFila = Double.parseDouble(modelo.getValueAt(1, i-1).toString());
           double CuartaFila =  8*TerceraFila;
           double QuintaFila = Math.ceil(SegundaFila/CuartaFila);
           double SextaFila = 0;
           double OctabaFila = 0;
           
           if(i>1){
               
               double value = Double.parseDouble((String)mimodelo.getValueAt(4, i-1).toString().trim())-QuintaFila;
               
               if(value>0){
                   
                   OctabaFila = value; 
                   
               }else if(value <0){
                   SextaFila = -value;
           
                }
           
           }
           
           double SeptimaFila = SextaFila*btn_costo_capacitacion;
           double NovenaFila = OctabaFila*btn_costo_despido;
           double DecimaFila = SegundaFila*btn_costo_tiempo_normal;
           double OnceabaFila = SeptimaFila+NovenaFila+DecimaFila;
           tot+=OnceabaFila;
           mimodelo.setValueAt(PrimeraFila, 0, i);
           mimodelo.setValueAt(SegundaFila, 1, i);
           mimodelo.setValueAt(TerceraFila, 2, i);
           mimodelo.setValueAt(CuartaFila, 3, i);
           mimodelo.setValueAt(QuintaFila, 4, i);
           mimodelo.setValueAt(SextaFila, 5, i);
           mimodelo.setValueAt(SeptimaFila, 6, i);
           mimodelo.setValueAt(OctabaFila, 7, i);
           mimodelo.setValueAt(NovenaFila, 8, i);
           mimodelo.setValueAt(DecimaFila, 9, i);
           mimodelo.setValueAt(OnceabaFila, 10, i);
           btn_inventario_inicial  = dato_1;
           
        }
        
        mimodelo.setValueAt(tot, 11, 1);
        
        Metodo metodo = new Metodo();
        metodo.setVisible(true);
        VentanaPrincipal.fondoInternal.add(metodo);
        metodo.p = this;
        this.setVisible(false);
    
    }
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        
        jTable1.setDefaultRenderer(Object.class,new ColumnaRenderer());
        jTable1.setFocusable(true);
    }//GEN-LAST:event_jTable1MousePressed
    public final void Enabled(){
    
        jTextField10.setEnabled(false);
        jTextField11.setEnabled(false);
        jTextField12.setEnabled(false);
        jTextField13.setEnabled(false);
        jTextField14.setEnabled(false);
        jTextField15.setEnabled(false);
        jTextField16.setEnabled(false);
        jTextField17.setEnabled(false);
        jTextField18.setEnabled(false);
        jTextField19.setEnabled(false);
       
        
    
    }
    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
      
        
    }//GEN-LAST:event_jComboBox1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Numero_trab;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
