package Hibernate;
// Generated 15-abr-2016 11:59:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Datos generated by hbm2java
 */
public class Datos  implements java.io.Serializable {


     private Integer idDatos;
     private Jornada jornada;
     private Producto producto;
     private Float materiales;
     private Float mantenimientoInventario;
     private Float marginalInventarioAgotado;
     private Float marginalSubcontratacion;
     private Float contratacionCapacitacion;
     private Float despido;
     private Float horasLaborales;
     private Float tiempoNormal;
     private Float tiempoExtra;
     private Float inventarioSeguridad;
     private Set datosmeses = new HashSet(0);

    public Datos() {
    }

	
    public Datos(Jornada jornada, Producto producto) {
        this.jornada = jornada;
        this.producto = producto;
    }
    public Datos(Jornada jornada, Producto producto, Float materiales, Float mantenimientoInventario, Float marginalInventarioAgotado, Float marginalSubcontratacion, Float contratacionCapacitacion, Float despido, Float horasLaborales, Float tiempoNormal, Float tiempoExtra, Float inventarioSeguridad, Set datosmeses) {
       this.jornada = jornada;
       this.producto = producto;
       this.materiales = materiales;
       this.mantenimientoInventario = mantenimientoInventario;
       this.marginalInventarioAgotado = marginalInventarioAgotado;
       this.marginalSubcontratacion = marginalSubcontratacion;
       this.contratacionCapacitacion = contratacionCapacitacion;
       this.despido = despido;
       this.horasLaborales = horasLaborales;
       this.tiempoNormal = tiempoNormal;
       this.tiempoExtra = tiempoExtra;
       this.inventarioSeguridad = inventarioSeguridad;
       this.datosmeses = datosmeses;
    }
   
    public Integer getIdDatos() {
        return this.idDatos;
    }
    
    public void setIdDatos(Integer idDatos) {
        this.idDatos = idDatos;
    }
    public Jornada getJornada() {
        return this.jornada;
    }
    
    public void setJornada(Jornada jornada) {
        this.jornada = jornada;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Float getMateriales() {
        return this.materiales;
    }
    
    public void setMateriales(Float materiales) {
        this.materiales = materiales;
    }
    public Float getMantenimientoInventario() {
        return this.mantenimientoInventario;
    }
    
    public void setMantenimientoInventario(Float mantenimientoInventario) {
        this.mantenimientoInventario = mantenimientoInventario;
    }
    public Float getMarginalInventarioAgotado() {
        return this.marginalInventarioAgotado;
    }
    
    public void setMarginalInventarioAgotado(Float marginalInventarioAgotado) {
        this.marginalInventarioAgotado = marginalInventarioAgotado;
    }
    public Float getMarginalSubcontratacion() {
        return this.marginalSubcontratacion;
    }
    
    public void setMarginalSubcontratacion(Float marginalSubcontratacion) {
        this.marginalSubcontratacion = marginalSubcontratacion;
    }
    public Float getContratacionCapacitacion() {
        return this.contratacionCapacitacion;
    }
    
    public void setContratacionCapacitacion(Float contratacionCapacitacion) {
        this.contratacionCapacitacion = contratacionCapacitacion;
    }
    public Float getDespido() {
        return this.despido;
    }
    
    public void setDespido(Float despido) {
        this.despido = despido;
    }
    public Float getHorasLaborales() {
        return this.horasLaborales;
    }
    
    public void setHorasLaborales(Float horasLaborales) {
        this.horasLaborales = horasLaborales;
    }
    public Float getTiempoNormal() {
        return this.tiempoNormal;
    }
    
    public void setTiempoNormal(Float tiempoNormal) {
        this.tiempoNormal = tiempoNormal;
    }
    public Float getTiempoExtra() {
        return this.tiempoExtra;
    }
    
    public void setTiempoExtra(Float tiempoExtra) {
        this.tiempoExtra = tiempoExtra;
    }
    public Float getInventarioSeguridad() {
        return this.inventarioSeguridad;
    }
    
    public void setInventarioSeguridad(Float inventarioSeguridad) {
        this.inventarioSeguridad = inventarioSeguridad;
    }
    public Set getDatosmeses() {
        return this.datosmeses;
    }
    
    public void setDatosmeses(Set datosmeses) {
        this.datosmeses = datosmeses;
    }




}


