package Hibernate;
// Generated 04-18-2016 10:44:33 AM by Hibernate Tools 4.3.1



/**
 * DatosMes generated by hbm2java
 */
public class DatosMes  implements java.io.Serializable {


     private Integer idDatosMes;
     private DatosGenerales datosGenerales;
     private Mes mes;
     private int demanda;
     private int diasHabiles;

    public DatosMes() {
    }

    public DatosMes(DatosGenerales datosGenerales, Mes mes, int demanda, int diasHabiles) {
       this.datosGenerales = datosGenerales;
       this.mes = mes;
       this.demanda = demanda;
       this.diasHabiles = diasHabiles;
    }
   
    public Integer getIdDatosMes() {
        return this.idDatosMes;
    }
    
    public void setIdDatosMes(Integer idDatosMes) {
        this.idDatosMes = idDatosMes;
    }
    public DatosGenerales getDatosGenerales() {
        return this.datosGenerales;
    }
    
    public void setDatosGenerales(DatosGenerales datosGenerales) {
        this.datosGenerales = datosGenerales;
    }
    public Mes getMes() {
        return this.mes;
    }
    
    public void setMes(Mes mes) {
        this.mes = mes;
    }
    public int getDemanda() {
        return this.demanda;
    }
    
    public void setDemanda(int demanda) {
        this.demanda = demanda;
    }
    public int getDiasHabiles() {
        return this.diasHabiles;
    }
    
    public void setDiasHabiles(int diasHabiles) {
        this.diasHabiles = diasHabiles;
    }




}


