package Hibernate;
// Generated 16-abr-2016 20:57:58 by Hibernate Tools 4.3.1



/**
 * Datosmes generated by hbm2java
 */
public class Datosmes  implements java.io.Serializable {


     private Integer idDatosMes;
     private Jornada jornada;
     private Mes mes;
     private int demanda;
     private int diasHabiles;

    public Datosmes() {
    }

    public Datosmes(Jornada jornada, Mes mes, int demanda, int diasHabiles) {
       this.jornada = jornada;
       this.mes = mes;
       this.demanda = demanda;
       this.diasHabiles = diasHabiles;
    }
   
    public Integer getIdDatosMes() {
        return this.idDatosMes;
    }
    
    public void setIdDatosMes(Integer idDatosMes) {
        this.idDatosMes = idDatosMes;
    }
    public Jornada getJornada() {
        return this.jornada;
    }
    
    public void setJornada(Jornada jornada) {
        this.jornada = jornada;
    }
    public Mes getMes() {
        return this.mes;
    }
    
    public void setMes(Mes mes) {
        this.mes = mes;
    }
    public int getDemanda() {
        return this.demanda;
    }
    
    public void setDemanda(int demanda) {
        this.demanda = demanda;
    }
    public int getDiasHabiles() {
        return this.diasHabiles;
    }
    
    public void setDiasHabiles(int diasHabiles) {
        this.diasHabiles = diasHabiles;
    }




}


