package Hibernate;
// Generated 04-18-2016 10:44:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jornada generated by hbm2java
 */
public class Jornada  implements java.io.Serializable {


     private Integer idJornada;
     private int año;
     private Set datosGeneraleses = new HashSet(0);

    public Jornada() {
    }

	
    public Jornada(int año) {
        this.año = año;
    }
    public Jornada(int año, Set datosGeneraleses) {
       this.año = año;
       this.datosGeneraleses = datosGeneraleses;
    }
   
    public Integer getIdJornada() {
        return this.idJornada;
    }
    
    public void setIdJornada(Integer idJornada) {
        this.idJornada = idJornada;
    }
    public int getAño() {
        return this.año;
    }
    
    public void setAño(int año) {
        this.año = año;
    }
    public Set getDatosGeneraleses() {
        return this.datosGeneraleses;
    }
    
    public void setDatosGeneraleses(Set datosGeneraleses) {
        this.datosGeneraleses = datosGeneraleses;
    }




}


