package Hibernate;
// Generated 16-abr-2016 20:57:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jornada generated by hbm2java
 */
public class Jornada  implements java.io.Serializable {


     private Integer idJornada;
     private int año;
     private Set datosgeneraleses = new HashSet(0);
     private Set datosmeses = new HashSet(0);

    public Jornada() {
    }

	
    public Jornada(int año) {
        this.año = año;
    }
    public Jornada(int año, Set datosgeneraleses, Set datosmeses) {
       this.año = año;
       this.datosgeneraleses = datosgeneraleses;
       this.datosmeses = datosmeses;
    }
   
    public Integer getIdJornada() {
        return this.idJornada;
    }
    
    public void setIdJornada(Integer idJornada) {
        this.idJornada = idJornada;
    }
    public int getAño() {
        return this.año;
    }
    
    public void setAño(int año) {
        this.año = año;
    }
    public Set getDatosgeneraleses() {
        return this.datosgeneraleses;
    }
    
    public void setDatosgeneraleses(Set datosgeneraleses) {
        this.datosgeneraleses = datosgeneraleses;
    }
    public Set getDatosmeses() {
        return this.datosmeses;
    }
    
    public void setDatosmeses(Set datosmeses) {
        this.datosmeses = datosmeses;
    }




}


