package Hibernate;
// Generated 04-18-2016 10:44:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mes generated by hbm2java
 */
public class Mes  implements java.io.Serializable {


     private Integer idMes;
     private String nombre;
     private Set datosMeses = new HashSet(0);

    public Mes() {
    }

	
    public Mes(String nombre) {
        this.nombre = nombre;
    }
    public Mes(String nombre, Set datosMeses) {
       this.nombre = nombre;
       this.datosMeses = datosMeses;
    }
   
    public Integer getIdMes() {
        return this.idMes;
    }
    
    public void setIdMes(Integer idMes) {
        this.idMes = idMes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDatosMeses() {
        return this.datosMeses;
    }
    
    public void setDatosMeses(Set datosMeses) {
        this.datosMeses = datosMeses;
    }




}


