package Hibernate;
// Generated 16-abr-2016 20:57:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mes generated by hbm2java
 */
public class Mes  implements java.io.Serializable {


     private Integer idMes;
     private String nombre;
     private Set datosmeses = new HashSet(0);

    public Mes() {
    }

	
    public Mes(String nombre) {
        this.nombre = nombre;
    }
    public Mes(String nombre, Set datosmeses) {
       this.nombre = nombre;
       this.datosmeses = datosmeses;
    }
   
    public Integer getIdMes() {
        return this.idMes;
    }
    
    public void setIdMes(Integer idMes) {
        this.idMes = idMes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDatosmeses() {
        return this.datosmeses;
    }
    
    public void setDatosmeses(Set datosmeses) {
        this.datosmeses = datosmeses;
    }




}


