package Hibernate;
// Generated 04-18-2016 10:44:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String codigo;
     private String nombre;
     private String descripcion;
     private Set datosGeneraleses = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String codigo) {
        this.codigo = codigo;
    }
    public Producto(String codigo, String nombre, String descripcion, Set datosGeneraleses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.datosGeneraleses = datosGeneraleses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDatosGeneraleses() {
        return this.datosGeneraleses;
    }
    
    public void setDatosGeneraleses(Set datosGeneraleses) {
        this.datosGeneraleses = datosGeneraleses;
    }




}


