package Hibernate;
// Generated 15-abr-2016 11:59:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String codigo;
     private String nombre;
     private String descripcion;
     private Set datoses = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Producto(String codigo, String nombre, String descripcion, Set datoses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.datoses = datoses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDatoses() {
        return this.datoses;
    }
    
    public void setDatoses(Set datoses) {
        this.datoses = datoses;
    }




}


