package Hibernate;
// Generated 16-abr-2016 20:57:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String codigo;
     private String nombre;
     private String descripcion;
     private Set datosgeneraleses = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String codigo) {
        this.codigo = codigo;
    }
    public Producto(String codigo, String nombre, String descripcion, Set datosgeneraleses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.datosgeneraleses = datosgeneraleses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDatosgeneraleses() {
        return this.datosgeneraleses;
    }
    
    public void setDatosgeneraleses(Set datosgeneraleses) {
        this.datosgeneraleses = datosgeneraleses;
    }




}


